#!/usr/bin/env Rscript
#
# Author: Miiko
#
#Fold difference = 2-ΔΔCt
# Principle:
# (calibrator is the matching control sample)
# (GOI is the ORI, norm is the non-ORI)
# ΔCt sample - ΔCt calibrator = ΔΔCt
# Ct GOI_s - Ct norm_s = ΔCt sample
# Ct GOI_c - Ct norm_c = ΔCt calibrator

suppressPackageStartupMessages(library(optparse))
suppressPackageStartupMessages(library(tidyverse))

# FUNCTIONS

# Helper function to get dataframe for origin Cqs
getOriginCqs <- function( origin, sampletype ){
  sampletype <- sampletype
  origins.df <- c()
  attach(input.df)
  for ( n in origin ){
    ori <- input.df[ which( input.df$detector == n & input.df$sample == sampletype ), c(1,3)]
    origins.df <- rbind(origins.df, ori)
  }
  detach(input.df)
  return(origins.df)
}

# Helper function to get dataframe for non-origin Cqs
getNonOriginCqs <- function( nonorigin, sampletype ){
  sampletype <- sampletype
  nonOrigins.df <- c()
  attach(input.df)
  for ( n in nonorigin ){
    nonori <- input.df[ which( input.df$detector == n & input.df$sample == sampletype ), c(1,3)]
    nonOrigins.df <- rbind(nonOrigins.df, nonori)
  }
  detach(input.df)
  return(nonOrigins.df)
}

# Helper function to get deltaCqs between ori-nonOri
getDeltaCqs <- function(origin, nonorigin){
  Cq.vector <- c()
  nameNonOri.vector <- c()
  nameOri.vector <- c()
  for (i in 1:nrow(nonorigin)){
    nameNonOri <- as.character(nonorigin[i,1])
    cq <- as.numeric(nonorigin[i,2])
    for ( j in 1:nrow(origin)){
      dCq <- origin[j,2] - cq
      Cq.vector <- append(Cq.vector, dCq)
      nameOri <- as.character(origin[j,1])
      nameNonOri.vector <- append(nameNonOri.vector, nameNonOri)
      nameOri.vector <- append(nameOri.vector, nameOri)
    }
  }
  deltaCq.df <- data.frame("ori" = nameOri.vector, "nonOri" = nameNonOri.vector, "dCq" = Cq.vector)
  return(deltaCq.df)
}

# Main function to get a dataframe of delta-deltaCqs
getDeltaDeltaCq <- function(originlist, nonoriginlist, sample, control){

  ori.X <- getOriginCqs(originlist, sample)
  nonOri.X <- getNonOriginCqs(nonoriginlist, sample)

  deltaCq.X <- getDeltaCqs(ori.X, nonOri.X)

  deltaDeltaCq <- deltaCq.X
  
  deltaDeltaCq <- mutate(deltaDeltaCq, foldEnrichm = 2^-dCq)
  deltaDeltaCq <- deltaDeltaCq[,c(1,2,4)]
  colnames(deltaDeltaCq) <- c("origin", "normalizer", "foldEnrichm")
  write.table(deltaDeltaCq, file.path("output_ddCq/foldEnrichment.csv"),
                sep =',', row.names = FALSE)
    # plot <- ggplot(deltaDeltaCq, aes(cycleNr, flValue, col = sample, group = well)) +
    #   geom_line() +
    #   theme_classic(14)
    # ggsave(filename = paste(detector, ".tif", sep=""),
    #        device = "tiff", path = "output_flGraphs",
    #        dpi = 100, width = 12, height = 10, units = "in")
    # } else {
    # stop("Error")
    # }
  }

# COMMAND LINE ARGUMENTS
list.options <- list( 
  make_option(c("-i", "--input"), type="character", default = "output_Cq/table_Cq.csv",
              help="Input file obtained from using get_CqValues_fromRawdata.R.
              Default name is table_Cq.csv in dir output_Cq (generated by the above Cq-sript).",
              metavar="table_Cq.csv"),
  make_option(c("-d", "--detectors"), type="character", default = "/Users/Miiko/software/own/qpcr/yeastORI_detector_table.csv",
              help="A csv file which specifies detector names used
              for origins and nonorigins, in columns 1 and 2, respectively.
              Default is yeastORI_detector_table.csv, which contains detectors ARS316, CTR315,
              ARS318, CTR319 and ARS319",
              metavar="detector_table.csv"),
  make_option(c("-x", "--sample"), type="character",
              help="Specify the name of the sample, often designated as X",
              metavar="Sample-X")
  )
opt <- parse_args(OptionParser(option_list=list.options))


# DEFINE DIRECTORIES AND GET THE DATA
setwd(getwd())
dir.create("output_ddCq", showWarnings = FALSE)

input.file <- opt$input
input.df <- read.csv(input.file, header = TRUE,
                     colClasses = c("factor", "factor", "NULL",
                                    "NULL", "numeric", "NULL"))
detector.file <- opt$detectors
origins.vector <- read.csv(detector.file, header = TRUE,
                           colClasses = c("character", "NULL"),
                           col.names = c("origins", "V2"))
origins.vector <- origins.vector$origins
nonorigins.vector <- read.csv(detector.file, header = TRUE,
                              colClasses = c("NULL", "character"),
                              col.names = c("V1", "nonorigins"))
nonorigins.vector <- nonorigins.vector$nonorigins
sampleX.name <- as.character(opt$sample)

# EXECUTE
getDeltaDeltaCq(origins.vector, nonorigins.vector, sampleX.name, sampleC.name)


# # TEMP define objects
# setwd("/Users/Miiko/temp")
# input.file <- "/Users/Miiko/Documents/projects/ns-seq_method-dev/troubleshooting/2018-12-05_fullNS/qpcr/output_Cq/table_Cq.csv"
# detector.file <- "/Users/Miiko/software/own/qpcr/yeastORI_detector_table.csv"
# sampleX.name <- as.character("NS")
# sampleC.name <- as.character("EdUPOS")
